CREATE TABLE IF NOT EXISTS Zhanr(zhanrID SERIAL PRIMARY KEY, name VARCHAR NOT NULL);

CREATE TABLE IF NOT EXISTS Ispolnitel(ispolnitelID SERIAL PRIMARY KEY, name VARCHAR NOT NULL);

CREATE TABLE IF NOT EXISTS ZhanrIspolnitel(id BIGSERIAL PRIMARY KEY, zhanrID INTEGER NOT NULL REFERENCES Zhanr(zhanrID), ispolnitelID INTEGER NOT NULL REFERENCES Ispolnitel, UNIQUE (zhanrID,ispolnitelID));
    
CREATE TABLE IF NOT EXISTS Albom(albomID SERIAL PRIMARY KEY,name VARCHAR NOT NULL,year_pr INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS AlbomIspolnitel(id BIGSERIAL PRIMARY KEY,albom_id INTEGER NOT NULL REFERENCES Albom,ispolnitel_id INTEGER NOT NULL REFERENCES Ispolnitel,UNIQUE (albom_id,ispolnitel_id));
                
CREATE TABLE IF NOT EXISTS Trek(trekID SERIAL PRIMARY KEY,naimenovanie VARCHAR NOT NULL,trekz INTEGER NOT NULL REFERENCES Albom(albomID),dlitelnost NUMERIC(2,1) NOT NULL);

create TABLE IF NOT EXISTS Sbornik(sbonikID SERIAL PRIMARY KEY,namer VARCHAR(50) NOT NULL,year_v INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS TrekSbornik(dis BIGSERIAL PRIMARY KEY,idt INTEGER NOT NULL REFERENCES Trek,ids INTEGER NOT NULL REFERENCES Sbornik,UNIQUE (idt,ids));